#region NonPlayableCharacters
default aaron = Aaron()
default adam = Adam()
default amber = Amber()
default anon = Anon()
default aryssa = Aryssa()
default aubrey = Aubrey()
default autumn = Autumn()
default beth = Beth()
default buyer = Buyer()
default caleb = Caleb()
default cameron = Cameron()
default candy = Candy()
default charli = Charlie()
default chloe = Chloe()
default chris = Chris()
default dean = Dean()
default elijah = Elijah()
default emily = Emily()
default emmy = Emmy()
default evelyn = Evelyn()
default faris = Faris()
default grayson = Grayson()
default imre = Imre()
default iris = Iris()
default jenny = Jenny()
default josh = Josh()
default julia = Julia()
default kai = Kai()
default kim = Kim()
default kourtney = Kourtney()
default lauren = Lauren()
default lews_official = LewsOfficial()
default lindsey = Lindsey()
default mason = Mason()
default mr_lee = MrLee()
default ms_rose = MsRose()
default naomi = Naomi()
default nora = Nora()
default parker = Parker()
default penelope = Penelope()
default perry = Perry()
default polly = Polly()
default riley = Riley()
default ryan = Ryan()
default samantha = Samantha()
default satin = Satin()
default sebastian = Sebastian()
default svc_housing_officer = SVCHousingOfficer()
default tom = Tom()
default trainer = Trainer()
default wolf = Wolf()
#endregion NonPlayableCharacters

#region PlayableCharacters
default name = "Alex"
default mc = MainCharacter()
#endregion PlayableCharacters