#region NonPlayableCharacters
default aaron = NonPlayableCharacter(_("Aaron"), _("DoubleARon"))
default adam = NonPlayableCharacter(_("Adam"), _("A.D.A.M."))
default amber = NonPlayableCharacter(_("Amber"), _("Amber_xx"))
default aryssa = NonPlayableCharacter(_("Aryssa"))
default aubrey = NonPlayableCharacter(_("Aubrey"), _("Aubs123"))
default autumn = NonPlayableCharacter(_("Autumn"), _("Its_Fall"))
default beth = NonPlayableCharacter(_("Beth"))
default buyer = NonPlayableCharacter(_("Buyer"))
default caleb = NonPlayableCharacter(_("Caleb"), _("Aleb"))
default cameron = NonPlayableCharacter(_("Cameron"), _("Cameroon"))
default candy = NonPlayableCharacter(_("Candy"))
default charli = NonPlayableCharacter(_("Charli"), _("CharliAndTheCockFactory"))
default chloe = NonPlayableCharacter(_("Chloe"), _("Chloe101"))
default chris = NonPlayableCharacter(_("Chris"), _("Chriscuit"))
default dean = NonPlayableCharacter(_("Dean"))
default elijah = NonPlayableCharacter(_("Elijah"), _("Elijah_Woods"))
default emily = NonPlayableCharacter(_("Emily"), _("emilyyyy"))
default emmy = NonPlayableCharacter(_("Emmy"))
default evelyn = NonPlayableCharacter(_("Evelyn"))
default grayson = NonPlayableCharacter(_("Grayson"), _("G-rayson"))
default imre = NonPlayableCharacter(_("Imre"), _("BadBoyImre"))
default iris = NonPlayableCharacter(_("Iris"))
default jenny = NonPlayableCharacter(_("Jenny"))
default josh = NonPlayableCharacter(_("Josh"), _("Josh80085"))
default julia = NonPlayableCharacter(_("Julia"))
default kai = NonPlayableCharacter(_("Kai"), _("KaiCriesWith2Ply"))
default kim = NonPlayableCharacter(_("Kim"), _("KimPlausible"))
default kourtney = NonPlayableCharacter(_("Kourtney"))
default lauren = NonPlayableCharacter(_("Lauren"), _("LoLoLauren"))
default lews_official = NonPlayableCharacter(_("LewsOfficial"))
default lindsey = NonPlayableCharacter(_("Lindsey"), _("LindsLou"))
default mason = NonPlayableCharacter(_("Mason"), _("Mason_Mas"))
default mr_lee = NonPlayableCharacter(_("Mr Lee"))
default ms_rose = NonPlayableCharacter(_("Ms Rose"))
default naomi = NonPlayableCharacter(_("Naomi"), _("NaomiXMarie"))
default nora = NonPlayableCharacter(_("Nora"), _("Nora_12"))
default parker = NonPlayableCharacter(_("Parker"))
default penelope = NonPlayableCharacter(_("Penelope"), _("Penelopeeps"))
default polly = NonPlayableCharacter(_("Polly"))
default riley = NonPlayableCharacter(_("Riley"), _("RileyReads"))
default ryan = NonPlayableCharacter(_("Ryan"), _("Ryanator"))
default samantha = NonPlayableCharacter(_("Samantha"), _("SamFromSpaceJam"))
default satin = NonPlayableCharacter(_("Satin"))
default sebastian = NonPlayableCharacter(_("Sebastian"), _("Big Seb"))
default tom = NonPlayableCharacter(_("Tom"))
default trainer = NonPlayableCharacter(_("Trainer"))
default wolf = NonPlayableCharacter(_("Wolf"))
#endregion NonPlayableCharacters

#region PlayableCharacters
default name = "Alex"
default mc = PlayableCharacter()
#endregion PlayableCharacters